# Author: Brice BOPDA
name: CI on GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: my jobs
    runs-on: [ubuntu-latest, windows-latest]
    
    services:
      postgres: 
        image: postgres:alpine
        ports: 
          - 5432:5432  # Adjusted to the default PostgreSQL port
        env:
          POSTGRES_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
          POSTGRES_USER: ${{ secrets.CI_DB_USER }}

    steps:
      - uses: actions/checkout@v4

      - name: Use latest node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x  # Node version should be a valid semantic version

      - name: Install dependencies
        run: npm install

      - name: Launch tests
        run: npm test

      - name: Start Docker services
        run: docker-compose -f docker-compose.build.yml up -d

      - name: Stop Docker services
        if: always()  # Ensures Docker is stopped even if the tests fail
        run: docker-compose -f docker-compose.build.yml down
